### ISSUE TITLE
[BUG] `env`브랜치 없음

### ISSUE THREAD

**Issue by ssaru** [HephaestusProject/pytorch-HarmonicCNN#1]
## 🐛 Bug

@Dohppak  승헌님, 레파지토리에 `env`브랜치가 없습니다.
Template 레포 사용하실 때, **Include all branches** 마크하셔서 생성 부탁드리겠습니다. 🙏

현 레포는 다시 만드시거나, 아니면 env 브랜치로 분기하셔서 Push하는 작업을 해야할 것 같습니다.

`env`레포는 추후, 쿠버네티스로 배포될 때, 사용할 릴리즈 브랜치 개념이라고 보시면 될 것 같습니다.

## To Reproduce

버그를 재현하기 위한 재현절차를 작성해주세요.

1.
2.
3.

## Environment

실행한 환경을 확인하기 위해 아래 체크리스트를 작성해주세요.

 - 운영체제 (e.g., Linux):
 - GPU 모델:
 - 기타 다른 정보:

**Comment by seungheondoh** [comment]
@ssaru 확인했습니다! 저녁에 작업하면서 다시 레포를 만들도록하겠습니다.

**Comment by seungheondoh** [comment]
@ssaru 레포 삭제권한이 없어서, env branch를 만들었습니다

**Comment by ssaru** [comment]
@Dohppak 확인했습니다. 🙌
이슈 닫겠습니다.
